import type { Metadata } from "next";
import Navbar from "@/components/ui/navbar";
import '@/app/globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isRootPage =
    typeof window !== "undefined" && window.location.pathname === "/";

  return (
    <html lang="en">
      <head></head>
      <body className="bg-gray-900 min-h-screen" style={{ fontFamily: "var(--font-geist-sans)" }}>
        <div className="min-h-screen flex flex-col">
          {!isRootPage && <Navbar />}{" "}
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
